//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turism
{
    using System;
    using System.Collections.Generic;
    
    public partial class Putevka
    {
        public int idPut { get; set; }
        public int idMarsh { get; set; }
        public int idTurist { get; set; }
        public Nullable<double> sumStoimost { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateFinish { get; set; }
    
        public virtual Marshrut Marshrut { get; set; }
        public virtual Turist Turist { get; set; }
    }
}
